apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-rtdn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-rtdn
    app.kubernetes.io/part-of: bryans-feb-23-app
  name: devfile-sample-rtdn
  namespace: bflorkie-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: devfile-sample-rtdn
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: devfile-sample-rtdn
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:bflorkie-tenant-devfile-sample-rtdn
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 3001
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 3001
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
